### PR TITLE
adds userID prop

### PR DESCRIPTION
**Pull request by anthonyle910**
Co-authored-by: Cyrux Lam <cyrux@live.com>
Co-authored-by: Tristan Bott <tristanbott30@gmail.com>
Co-authored-by: Daniel Park <119081299+parkdaniel731@users.noreply.github.com>
Co-authored-by: Christopher Park <cp3063@columbia.edu>

### CODE REVIEW

**Review by trisbt — APPROVED** [review]
Looks good nice work!

**Review by cyduckk — APPROVED** [review]
looks good!

**Review by ChristopherPark3 — APPROVED** [review]
Nice job!

**Review by parkdaniel731 — APPROVED** [review]
Looks good!

**Pull request merged**
