### PR TITLE
Anthony/middleware

### PR DESCRIPTION
**Pull request by anthonyle910**
Co-authored-by: Tristan Bott <[tristanbott30@gmail.com](mailto:tristanbott30@gmail.com)>

### CODE REVIEW

**Review by trisbt — APPROVED** [review]
Looks good!

**Review by cyduckk — APPROVED** [review]
looks good!

**Review by parkdaniel731 — APPROVED** [review]
Looks good!

**Review by ChristopherPark3 — APPROVED** [review]
Looks great guys!

**Pull request merged**
